import express from "express";
import { removeBlog , addBlog , editBlog , getbyid , getmyblog , getallblog} from "../controller/blog.controller.js";
import { authentication } from "../middleware/authentication.js";
import authorization from "../middleware/authorization.js";
const blogroutes = express();
blogroutes.post("/create" , authentication , authorization('admin', 'writer'), addBlog );
blogroutes.get("/getbyid/:id" , authentication , getbyid);
blogroutes.get("/getall" , authentication , getallblog);
blogroutes.get("/getmyblog" , authentication , authorization('admin', 'writer'), getmyblog);
blogroutes.delete("/delete/:id" , authentication , authorization('admin', 'writer'),removeBlog);
blogroutes.patch("/edit/:id"  , authentication , authorization('admin', 'writer'),editBlog);
export default blogroutes;